voting/auth.py
import functools

from flask import (
    Blueprint, flash, g, redirect, render_template, request, session, url_for, current_app
)
from werkzeug.security import check_password_hash

from voting.db import get_db
# from sqlite3 import OperationalError

bp = Blueprint('auth', __name__, url_prefix='/auth')


@bp.route('/login', methods=('GET', 'POST'))
def login():
    if request.method == 'POST':
        error = None
        category = ''
        if request.form.get('username') == '':
            error = "Bitte Benutzernamen eingeben!"
            category = 'error'

        if request.form.get('password') == '':
            error = "Bitte Passwort eingeben!"
            category = 'error'

        # neither username or password are empty
        if error is None:
            password = request.form.get('password', default='')
            username = request.form.get('username')
            db = get_db()

            # check if user is admin user and render admin-page
            admin = db.execute(
                'SELECT * FROM  admin WHERE username = ?', (username,)).fetchone()
            if admin and check_password_hash(admin['password_hash'], password):
                # successfully logged in as admin user
                session.clear()
                session['admin'] = True
                session['admin_name'] = admin['username']
                # set session object if courses have already been calculated before
                session['courses_calculated'] = db.execute(
                    "SELECT COUNT(*) FROM user WHERE final_course != 'LEER'"
                ).fetchone()[0] > 0
                return redirect(url_for('views.admin_page'))
            user = db.execute(
                'SELECT * FROM user WHERE username = ?', (username,)
            ).fetchone()

            # case for not signed in successfully, error is set to value
            if user is None:
                error = 'Falscher Benutzername'
                category = 'danger'
            elif not check_password_hash(user['password_hash'], password):
                error = 'Falsches Passwort'
                category = 'danger'

            # case that a user is successfully logged_in
            if error is None:
                session.clear()
                # set the session['user_id'] value correct:
                session['user_id'] = user['id']
                flash("Erfolgreich eingeloggt", 'success')
                return redirect(url_for('views.index'))

        flash(error, category=category)

    # case for request.method == 'GET'
    return render_template('auth/login.html', active_page='login')


@bp.route('/logout')
def logout():
    session.clear()
    return redirect(url_for('views.index'))


@bp.before_app_request
def load_logged_in_user():
    user_id = session.get('user_id')
    if user_id is None:
        g.user = None
    else:
        g.user = get_db().execute(
            'SELECT * FROM user WHERE id = ?', (user_id,)
        ).fetchone()

# decorator for each view, that requires a login.
def login_required(view):
    @functools.wraps(view)
    def wrapped_view(**kwargs):
        if g.user is None:
            # redirect to login if user is not loaded
            flash("Bitte vorher einloggen.", category="info")
            return redirect(url_for('auth.login'))
        # return original view, if user id logged in
        return view(**kwargs)

    return wrapped_view

# decorator for each view that requires an admin
def admin_required(view):
    @functools.wraps(view)
    def wrapped_view(**kwargs):
        if not session.get('admin'):
            # redirect to '/' if not an admin user
            flash("Permission denied. Please login as admin user", category="info")
            return redirect(url_for('views.index'))
        # return original view, if user is admin:
        return view(**kwargs)
    return wrapped_view

voting/views.py
from flask import (
    Blueprint, flash, g, redirect, render_template, request, session, url_for
)
from voting.db import get_db
from voting.helpers import is_username_taken, add_user_to_database, get_query_for_nth_vote, calculate_courses
from voting.auth import login_required, admin_required
from voting.models import get_courses_list
from voting.cache import get_cached_classes, get_cache
from datetime import datetime, timedelta, timezone

bp = Blueprint('views', __name__)

cache = get_cache()

@bp.route('/')
def index():
    user = None
    if g.user:
        user = g.user
        user_id = g.user['id']
        if g.user['vote_passed'] == 1:
            db = get_db()
            vote = db.execute(
                "SELECT * FROM vote WHERE user_id = ?", (user_id,)).fetchone()
            return render_template('views/voted.html', vote=vote)
    return render_template('views/index.html', user=user, active_page='index')


@bp.route('/vote', methods=('GET', 'POST'))
@login_required
def vote():
    grade = int(g.user['class'][:-1])
    if request.method == 'GET':
        return render_template('views/vote.html', active_page='vote', grade=grade, courses = get_courses_list())

    # case for POST
    else:
        wahl_1 = request.form.get("wahl1")
        wahl_2 = request.form.get("wahl2")
        wahl_3 = request.form.get("wahl3")
        error = None

        votes_list = [wahl_1, wahl_2, wahl_3]
        # check that a vote for every choice has been made:
        if None in votes_list:
            error = "Mindestens ein Kurs nicht ausgewählt. Bitte wiederholen"

        # check for no duplicates
        elif len(votes_list) != len(set(votes_list)):
            error = "Mindestens ein Kurs doppelt gewählt"

        # check that only courses that contains users class are in vote
        if error is None:
            for course in get_courses_list():
                if course.name in votes_list:
                    if grade not in course.classes:
                        error = "Mindestens ein Kurs ist nicht für deinen Jahrgang vorgesehen."
                        break

        if error is None:
            db = get_db()
            id = g.user['id']
            # update if vote already passed
            if g.user['vote_passed'] == 1:
                db.execute(
                    "UPDATE vote SET first_vote = ?, second_vote = ?, third_vote = ?,"
                    "date_created = datetime('now', 'localtime')"
                    "WHERE user_id = ?",
                    (wahl_1, wahl_2, wahl_3, id)
                )
                flash("Deine Wahl wurde aktualisiert", "success")

            # save first votes into vote-table in db
            else:
                db.execute(
                    "INSERT INTO vote (user_id, date_created, first_vote, second_vote, third_vote)"
                    "VALUES (?,datetime('now', 'localtime'),?,?,?)",
                    (id, wahl_1, wahl_2, wahl_3)
                )
                # update vote_passed for user
                db.execute(
                    "UPDATE user SET vote_passed = 1 WHERE id = ?",
                    (id,)
                )
                flash("Deine Wahl wurde gespeichert", "success")

            db.commit()
            return redirect(url_for('views.index'))
        flash(error, "warning")
        return render_template('views/vote.html')


@bp.route("/course-overview")
@cache.cached(timeout=50)
def overview():
    return render_template('views/courses.html', active_page='overview', courses = get_courses_list())


# Admin pages

@bp.route("/admin",)
@admin_required
def admin_page():
    return render_template('views/admin/admin.html')


@bp.route("/admin/add-student", methods=('GET', 'POST'))
@admin_required
def add_student():
    # case for adding a new student:
    classes = get_cached_classes()
    if request.method == 'POST':
        error = None
        student_class = request.form.get('class')
        if student_class != None:
            student_class = student_class.replace("('", "")
            student_class = student_class.replace("',)", "")

        entries = {'first_name': request.form.get('first_name'),
                   'last_name': request.form.get('last_name'),
                   'username': request.form.get('username'),
                   'password': request.form.get('password'),
                   'password_check': request.form.get('password_check'),
                   'class': student_class
                   }
        for entry in entries:
            if entries[entry] is None:
                error = 'Mindestens ein Eintrag nicht ausgefüllt'
                break
            else:
                entries[entry] = entries[entry].strip()  # type: ignore

        db = get_db()
        if error is None and entries['password']:
            if entries['password'] != entries['password_check']:
                error = 'Fehler bei der Wiederholung des Passworts'
            elif len(entries['password']) < 5:
                error = 'Passwort muss mindestens 5 Zeichen lang sein. Bitte wiederholen'
            # check that 'class' is valid
            elif is_username_taken(entries['username'], db):
                error = 'Benutzername bereits vergeben'

            if error is None:
                if any(student_class in value for value in classes):
                    error = None
                else:
                    error = 'Klasse ungültig'

        # add user to database
        if error is None:
            add_user_to_database(entries['first_name'], entries['last_name'],
                                 entries['username'], entries['password'], entries['class'], db)
            flash('Neuer Schüler erfolgreich hinzugefügt', 'success')
            return redirect(url_for('views.admin_page'))

        else:
            flash(error, 'warning')
            return redirect(url_for('views.add_student'))

    # case for 'GET'
    return render_template('views/admin/add_student.html', active_page='add-student', classes=classes)


@bp.route("/admin/delete-student/all-students", methods=('GET', 'POST'))
@admin_required
def delete_student_from_class():
    if request.method == 'POST':
        selected_students_ids = request.form.getlist('selected_students')
        if len(selected_students_ids) != 0:
            db = get_db()
            for id in selected_students_ids:
                db.execute("DELETE FROM user WHERE id = ?", (id,))
            db.commit()
            if len(selected_students_ids) <= 1:
                flash('Schüler wurde erfolgreich aus Datenbank gelöscht', 'info')
            else:
                flash('Schüler wurden erfolgreich aus Datenbank gelöscht', 'info')
        else:
            flash('No user selected', 'info')
        return redirect(url_for('views.admin_page'))

    # GET
    db = get_db()
    student_class = request.args['student_class']
    students = db.execute(
        "SELECT id, first_name, last_name, class FROM user WHERE class = ? ORDER BY last_name ASC", (student_class,)).fetchall()

    return render_template('views/admin/students_by_class_delete.html', active_page='delete-student', student_class=student_class, students=students)


@bp.route("/admin/delete-student", methods=('GET', 'POST'))
@admin_required
def delete_student():
    if request.method == 'POST':
        student_class = request.form.get('class')
        if student_class != None:
            student_class = student_class.replace("('", "")
            student_class = student_class.replace("',)", "")
        else:
            flash('No class selected or class not in database' 'error')
            return redirect(url_for('views.admin_page'))
        return redirect(url_for('views.delete_student_from_class', active_page='delete-student', student_class=student_class))
    return render_template('views/admin/delete_student.html', active_page='delete-student', classes=get_cached_classes())


@bp.route("/admin/class-results", methods=('GET', 'POST'))
@admin_required
def class_results():
    if request.method == 'POST':
        selected_class = request.form.get('selected_class')
        db = get_db()
        class_results = db.execute(
            "SELECT first_name, last_name, vote_passed, first_vote, second_vote, third_vote from user INNER JOIN vote ON user.id = vote.user_id WHERE class = ? AND vote_passed = 1 ORDER BY last_name", (selected_class,)).fetchall()
        return render_template('views/admin/show_results_per_class.html', active_page='class-results', class_results=class_results, selected_class=selected_class)
    # case for 'GET'
    return render_template('views/admin/choose_class.html', active_page='class-results', classes=get_cached_classes())


@bp.route("/admin/course-results", methods=('GET', 'POST'))
@admin_required
def course_results():
    if request.method == 'POST':
        selected_course = request.form.get('selected_course')
        # Fetch data from the database based on the selected course
        db = get_db()
        # First_vote-query
        query_first = get_query_for_nth_vote('first_vote')
        results_first = db.execute(query_first, (selected_course,)).fetchall()
        query_second = get_query_for_nth_vote('second_vote')
        results_second = db.execute(
            query_second, (selected_course,)).fetchall()
        query_third = get_query_for_nth_vote('third_vote')
        results_third = db.execute(query_third, (selected_course,)).fetchall()
        return render_template('views/admin/show_results_per_course.html', active_page='course-results', selected_course=selected_course, results_first=results_first, results_second=results_second, results_third=results_third)
    # case for 'GET'
    return render_template('views/admin/get_results_per_course.html', active_page='course-results', courses = get_courses_list())


@bp.route("/admin/course-proposal", methods=('GET', 'POST'))
@admin_required
def course_proposal():
    if request.method == 'POST':

voting/templates/admin_base.html
<!DOCTYPE html>

<html lang="en">
  <head>
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3"
      crossorigin="anonymous"
    />
    <meta name="viewport" content="initial-scale=1, width=device-width" />
    <link
      href="{{ url_for('static', filename='styles.css') }}"
      rel="stylesheet"
    />
    <link
      rel="shortcut icon"
      href="{{ url_for('static', filename='favicon.ico') }}"
    />
    <title>Schaumburg wählt: Admin {% block title %} {% endblock %}</title>
  </head>
  <body
    background="{{ url_for('static', filename='desktop_background_main.png') }}"
  >
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="container">
        <a
          href="{{ url_for('views.index') }}"
          class="navbar-brand mb-0"
          style="margin-right: 50px"
        >
          <img
            class="mb-2"
            src="../static/schaumburg_logo.png"
            width="30"
            height="30"
          />
          OS Schaumburger Strasse - ADMIN
        </a>
        <button
          type="button"
          data-bs-toggle="collapse"
          data-bs-target="#navbarNav"
          class="navbar-toggler"
          aria-controls="navbarNav"
          aria-expanded="false"
          aria-label="toggle navigation"
        >
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav">
            <li class="nav-item">
              <a class="nav-link" href="{{ url_for('auth.logout')}}">Logout</a>
            </li>
            <li class="nav-item">
              <a
                class="nav-link {% if active_page == 'add-student' %} active{% endif %}"
                href="{{ url_for('views.add_student')}}"
                >Schüler hinzufügen</a
              >
            </li>

            <li class="nav-item">
              <a
                class="nav-link {% if active_page == 'delete-student' %} active{% endif %}"
                href="{{ url_for('views.delete_student')}}"
                >Schüler löschen</a
              >
            </li>
            <li class="nav-item">
              <a
                class="nav-link {% if active_page == 'class-results' %} active{% endif %}"
                href="{{ url_for('views.class_results')}}"
                >Wahlergebnisse nach Klassen</a
              >
            </li>
            <li class="nav-item">
              <a
                class="nav-link {% if active_page == 'course-results' %} active{% endif %}"
                href="{{ url_for('views.course_results')}}"
                >Wahlergebnisse nach Kursen</a
              >
            </li>
            {% if session['courses_calculated'] %}
            <li class="nav-item">
              <a
                class="nav-link {% if active_page == 'course-proposal' %} active{% endif %}"
                href="{{ url_for('views.course_proposal')}}"
                >Kursvorschläge anzeigen</a
              >
            </li>
            {% endif %}
            <li class="nav-item">
              <a
                class="nav-link {% if active_page == 'calculate-courses' %} active{% endif %}"
                href="{{ url_for('views.calculate_cs')}}"
                >Kursvorschläge {% if session['courses_calculated'] %} neu {%
                endif %} berechnen</a
              >
            </li>
          </ul>
        </div>
      </div>
    </nav>
    <main>
      {% with messages = get_flashed_messages(with_categories=true) %} {% if
      messages %} {% for category, message in messages %}
      <div
        class="alert alert-{{ category }} alert-dismissible fade flash-2 show"
        role="alert"
      >
        {{message}}
        <button
          type="button"
          class="btn-close"
          data-bs-dismiss="alert"
          aria-label="Close"
        ></button>
      </div>
      {% endfor %} {% endif %} {% endwith %} {% block main %}{% endblock %}
    </main>
    {% block script %}{% endblock %}
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN"
      crossorigin="anonymous"
    ></script>
  </body>
</html>

voting/templates/base.html
<!DOCTYPE html>

<html lang="en">
  <head>
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3"
      crossorigin="anonymous"
    />
    <meta name="viewport" content="initial-scale=1, width=device-width" />
    <link
      href="{{ url_for('static', filename='styles.css') }}"
      rel="stylesheet"
    />
    <link
      rel="shortcut icon"
      href="{{ url_for('static', filename='favicon.ico') }}"
    />
    <title>Schaumburg wählt: {% block title %} {% endblock %}</title>
  </head>
  <body
    background="{{ url_for('static', filename='desktop_background_main.png') }}"
  >
  <!-- FIXME: The navbar is often above other stuff so that you cannot see that -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="container">
        <a
          href="{{ url_for('views.index') }}"
          class="navbar-brand mb-0"
          style="margin-right: 50px"
        >
          <img
            class="mb-2"
            src="../static/schaumburg_logo.png"
            width="30"
            height="30"
          />
          OS Schaumburger Strasse
        </a>
        <button
          type="button"
          data-bs-toggle="collapse"
          data-bs-target="#navbarNav"
          class="navbar-toggler"
          aria-controls="navbarNav"
          aria-expanded="false"
          aria-label="toggle navigation"
        >
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav">
            {% if g.user %}
            <li class="nav-item">
              <a class="nav-link" href="{{ url_for('auth.logout')}}">Logout</a>
            </li>
            {% else %}
            <li class="nav-item">
              <a class="nav-link {% if active_page == 'login' %} active{% endif %}" href="{{ url_for('auth.login')}}">Login</a>
            </li>
            {% endif %}
            <li class="nav-item">
              <a class="nav-link {% if active_page == 'vote' %} active{% endif %}" href="{{ url_for('views.vote')}}"
                >{% if g.user['vote_passed'] == 1 %}Wahl erneuern{% else %}Jetzt
                wählen{% endif %}</a
              >
            </li>
            <li class="nav-item">
              <a class="nav-link {% if active_page == 'overview' %} active{% endif %}" href="{{ url_for('views.overview')}}"
                >Kursübersicht</a
              >
            </li>
          </ul>
        </div>
      </div>
    </nav>
    <main>
      {% with messages = get_flashed_messages(with_categories=true) %} {% if
      messages %} {% for category, message in messages %}
      <div
        class="alert alert-{{ category }} alert-dismissible fade flash-2 show"
        role="alert"
      >
        {{message}}
        <button
          type="button"
          class="btn-close"
          data-bs-dismiss="alert"
          aria-label="Close"
        ></button>
      </div>
      {% endfor %} {% endif %} {% endwith %} {% block main %}{% endblock %}
    </main>
    {% block script %}{% endblock %}
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN"
      crossorigin="anonymous"
    ></script>
  </body>
</html>